export interface  CartItemInterface {
    cart_id: string,
    name?: string,
    sku?: string,
    qty:number,
    origin_price: number,
    row_total?: number,
    row_total_incl_tax?: number,
    origin_image?: string,
    base_row_total?: number,
    base_row_total_incl_tax?: number,
    is_refund_item: boolean,
    type_id?: string,
    product_id?: string,
    super_attribute?: any,
    bundle_option?: any,
    bundle_option_qty?: any,
    time: string,
    parent_id?: string,
    item_id?: string,
}
